# Generated by Django 5.0.7 on 2024-08-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_verificationcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
